require "nokogiri"
require "open-uri"
require_relative "../lib/beauty_product/cli"
require_relative "../lib/beauty_product/ingredient"
require_relative "../lib/beauty_product/product"
require_relative "../lib/beauty_product/scraper"
require_relative "../lib/beauty_product/version"
